[package]
name = "quake3-qvm-interpreter"
version = "0.1.0"
authors = ["robo9k <robo9k@symlink.io>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
